// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ADTTestModel
{
    partial class DomainClassWStateMachine
    {
        protected void ActionCreated()
        {
            // Action Description on Model as a reference.



        }

        protected void ActionWorking()
        {
            // Action Description on Model as a reference.



        }

        protected void ActionCompleted()
        {
            // Action Description on Model as a reference.



        }

    }
}
